bot_name: "schedule-bot"
workers:
  worker1:
    schedule_name: "Golf-Course"
    #slack_creds: #not recommended, use env-var SLACK_CREDS_WORKER1 instead
    #calendar_uuid: #not recommended, use env-var CALENDAR_UUID_WORKER1 instead
    #calendar_creds: #not recommended, use env-var CALENDAR_CREDS_WORKER1 instead
    max_spots_per_day: 8
    max_spots_per_week: 0
    max_spots_per_month: 0
    max_spots_per_year: 0
    max_reserved_per_person_per_reservation: 4
    max_reserved_per_reservation: 4
    max_individual_reservations_per_day: 0
    max_individual_reservations_per_week: 0
    max_individual_reservations_per_month: 0
    max_individual_reservations_per_year: 0
    allow_extended_reservations: True
    max_extended_resrvation_blocks: 2
    fill_last_minute_reservations: True
    fill_reservations: Ask
    max_time_in_future: 5w
    reservation_cooldown: 4w
    reservation_allowed_if_reservation_passed: True
    free_last_minute_scheduling: True
    last_minute_time_period: 5d
    last_minute_disclaimer: "This schedule is considered 'last minute'. It will not count against your total allowed schedules, but there is no guarantee that a time block  will still be available"
    require_slack_handle: False
    days-available: [mon, tue, wed, thu, fri]
    time-blocks-available: [9:00a-10:00a, 11:00a-12:00p]
    reminders_enabled: True
    reminders: [7d, 1d]
    allow_cancel_reservation: True
    cancel_non_aknowledged_reminders: True
    cancel_reservations_with_no_time_blocks: 3d
    aknowledge_grace_period: 3d
    job_schedule: 1d
    job_start: 8:00am
    job_end: 5:00pm

    #CUSTOM FUNCTIONS (Must also be enabled)
    custom_jobs: True
    custom_job_function: validate_tee_times
    custom_cancel_function: True
    cancel_function: fox-hollow-reschedule-flow
    external_scheduling: True
    external_scheduling_function: fox-hollow-scheduler
  worker2:
    schedule_name: "example-schedule"
    #slack_creds: #not recommended, use env-var SLACK_CREDS_WORKER2 instead
    #calendar_uuid: #not recommended, use env-var CALENDAR_UUID_WORKER2 instead
    #calendar_creds: #not recommended, use env-var CALENDAR_CREDS_WORKER2 instead
    max_spots_per_day: 0
    max_spots_per_week: 0
    max_spots_per_month: 0
    max_spots_per_year: 0
    max_reserved_per_person_per_reservation: 0
    max_reserved_per_reservation: 0
    max_individual_reservations_per_day: 0
    max_individual_reservations_per_week: 0
    max_individual_reservations_per_month: 0
    max_individual_reservations_per_year: 0
    allow_extended_reservations: True
    max_extended_resrvation_blocks: 2
    fill_last_minute_reservations: True
    fill_reservations: Ask
    max_time_in_future: 5w
    reservation_cooldown: 4w
    reservation_allowed_if_reservation_passed: True
    free_last_minute_scheduling: True
    last_minute_time_period: 5d
    last_minute_disclaimer: "This schedule is considered 'last minute'. It will not count against your total allowed schedules, but there is no guarantee that a time block  will still be available"
    require_slack_handle: False
    days-available: [mon, tue, wed, thu, fri]
    time-blocks-available: [9:00a-10:00a, 11:00a-12:00p]
    reminders_enabled: True
    reminders: [7d, 1d]
    allow_cancel_reservation: True
    cancel_non_aknowledged_reminders: True
    cancel_reservations_with_no_time_blocks: 0d
    aknowledge_grace_period: 3d
    job_schedule: 1d

    #CUSTOM FUNCTIONS (Must also be enabled)
    custom_jobs: True
    custom_job_function: validate_tee_times
    custom_cancel_function: True
    cancel_function: fox-hollow-reschedule-flow
    external_scheduling: True
    external_scheduling_function: fox-hollow-scheduler

